# Generated by Django 4.2.2 on 2023-06-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRB_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GRB_app.stores'),
        ),
    ]
