# Generated by Django 4.2.2 on 2023-06-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRB_app', '0002_books_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='store_id',
        ),
        migrations.AddField(
            model_name='books',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='GRB_app.stores'),
            preserve_default=False,
        ),
    ]
